# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


def api_key_load
    key_id = ENV["APP_STORE_CONNECT_KEY_ID"]
    issuer_id = ENV["APP_STORE_CONNECT_ISSUER_ID"]
    key_content = ENV["APP_STORE_CONNECT_P8"]

    app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_content: key_content,
      is_key_content_base64: true,
      in_house: false # Set to true if using an in-house (enterprise) account
    )
  end




platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    build_app(scheme: "ModernWeatherUI")
  end
end
