name: build app on push

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Select Xcode 16.4
        run: |
          sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
          xcodebuild -version
      
      - name: Build the project
        run: |
          xcodebuild \
            -project ModernWeatherUI.xcodeproj \
            -scheme "ModernWeatherUI" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            clean build

      - name: Run Unit Tests
        run: |
          xcodebuild \
            -project ModernWeatherUI.xcodeproj \ 
            -scheme "ModernWeatherUI" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            test

