name: build app on push

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      
      - name: Build the project
        run: |
          xcodebuild \
            -project ModernWeatherUI.xcodeproj \
            -scheme "ModernWeatherUI" \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            clean build

      - name: Run Unit Tests
        run: |
          xcodebuild \
            -project ModernWeatherUI.xcodeproj \ 
            -scheme "ModernWeatherUI" \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            test

